#!/usr/bin/env python
# File autogenerated by django-admin startproject dubus
import os
import sys

if __name__ == "__main__":
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "dubus.settings")

    from django.core.management import execute_from_command_line

    execute_from_command_line(sys.argv)
